services:
  app:
    build: ./app
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGO_URI
      - FLASK_ENV
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: