apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'flask-mongo-app'
        static_configs:
          - targets: ['flask-mongo-app-service:80']

      - job_name: 'mongodb-exporter'
        static_configs:
          - targets: ['mongodb-exporter:9216']