apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-mongo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-mongo-app
  template:
    metadata:
      labels:
        app: flask-mongo-app
    spec:
      containers:
        - name: flask-mongo-app
          image: flask-mongo-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo_uri
            - name: FLASK_ENV
              value: "development"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"