apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo_uri: bW9uZ29kYjovL3NreXdhbGxrZWU6TXlEM3ZPcHNGbDRzay1NMG5nMFRhc2tQNHNzQG1vbmdvZGI6MjcwMTcv
  mongo_username: c2t5d2FsbGtlZQ==
  mongo_password: TXlEM3ZPcHNGbDRzay1NMG5nMFRhc2tQNHNz
