apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
  labels:
    app: elasticsearch
spec:
  clusterIP: None
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport
  selector:
    app: elasticsearch