apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          - /var/log/flask_app.log
    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"]