apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: default
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      serviceAccountName: filebeat
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.10.0
          args: ["-e", "-E", "output.elasticsearch.hosts=[\"http://elasticsearch:9200\"]"]
          env:
            - name: ELASTICSEARCH_HOST
              value: "http://elasticsearch:9200"
          volumeMounts:
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
            - mountPath: /var/log
              name: log-volume
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: log-pvc
        - name: filebeat-config
          configMap:
            name: filebeat-config